language: php
dist: trusty
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "hhvm"

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover ./build/logs/clover.xml tests/

after_script:
  - php vendor/bin/coveralls -v