name: Unit Tests

on:
  push:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: |
          docker compose run --rm --user "0:0" cli composer install
          docker compose run --rm cli ./vendor/bin/phpunit tests/
